name = "ekosistem-bk"
main = "index.js"
compatibility_date = "2026-08-07"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "bk-database"
database_id = "38c05146-ecf7-4f22-b8de-60708f59de4e"